import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it, vi } from "vitest";

import RootLayout from "./layout";

vi.mock("next/font/google", () => ({
  Geist: () => ({ variable: "--font-geist-sans" }),
  Geist_Mono: () => ({ variable: "--font-geist-mono" }),
}));

describe("RootLayout", () => {
  it("defines site metadata", async () => {
    const { metadata } = await import("./layout");

    expect(metadata.title).toBe("Create Next App");
    expect(metadata.description).toBe("Generated by create next app");
  });

  it("renders children in the layout shell", () => {
    const html = renderToStaticMarkup(
      <RootLayout>
        <p>Travel app</p>
      </RootLayout>,
    );

    expect(html).toContain("Travel app");
    expect(html).toContain('lang="en"');
  });
});
